### ISSUE TITLE
MASS yields different results than brute force search

### ISSUE THREAD

**Issue by youzzefb** [target/matrixprofile-ts#33]
I observed different results when calculating the distance profile using the brute force search algorithm and the function matrixprofile.MASS.distance_profile(). Here is a sample of my code:

# calculate by brute force
query_ = (query - query.mean()) / query.std(ddof=0)
len_m = query.shape[0]
dist = []
for index in range(0, serie.shape[0] - len_m + 1):
    sub = serie[index:index + len_m]
    sub = (sub - sub.mean()) / sub.std(ddof=0)
    dist.append(np.sqrt(np.sum(np.power(sub - query_, 2))))
dist = np.array(dist)

This is less of an issue and more me trying to validate the work of a colleague who has already implemented a version of matrix profile. Given it has already been implemented by this group I thought it would be best to open up dialogue. Thanks!

**Comment by vanbenschoten** [comment]
Interesting...I'll take a look at this. Thanks for the heads up!

**Comment by tylerwmarrs** [comment]
@youzzefb I think that you may be calling the distance call incorrectly? Here is a sample notebook that shows the same results. In order to have the same array, you would need to pull the single values out of each array in the loop and append to a new list.

I hope this helps.

[Same Results.zip](https://github.com/target/matrixprofile-ts/files/2793858/Same.Results.zip)

**Comment by JaKasb** [comment]
Each version of the MatrixProfile algorithms produces different results.
Furthermore each version of MASS produces different results.

STAMP differs from naive bruteforce due to STAMP's FFT convolution
STOMP differs from STAMP due to error propagation and error accumulation.
I assume that SCRIMP also differs from STAMP and STOMP.

Never compare floating point numbers for exact equality.
The final question is: "Which algorithm produces the least numerical error". 
No algorithm computes "exactly" with floating point numbers.

**Comment by vanbenschoten** [comment]
I think the discussion above sufficiently answers the question. Closing the issue.
