### ISSUE TITLE
Speed claims

### ISSUE THREAD

**Issue by DieterDePaepe** [target/matrixprofile-ts#38]
In your [blog post](https://tech.target.com/2018/12/11/matrix-profile.html) you mention:

>  Astonishingly, we can process 20 years’ worth of data, sampled every five minutes, in less than 20 seconds. This speed is critical, as we expect that our data streams will expand in size by several orders of magnitude.

I would expect 20 years of data points to around 2M (12 * 24 * 365 * 20) or around 400K if you only measured workdays/hours. However, on my laptop it already takes 20 seconds to process 16K data points.

Did you use special libraries or hardware to achieve your timings?

**Comment by frankiecancino** [comment]
It was in 5 minute aggregations including weekends. (288/day * 7 * 4 * 12 * 20) = 1,935,360

And yes this was using the STOMP implementation that hasn't been released yet, since we are still making it sufficient for the API. Trying to call the CuDA code via Python interface and making it seamless and intuitive.

And yes, it was using an NVIDIA Tesla p100 GPU I believe. It was either a k80 or p100.
