### ISSUE TITLE
support for multi-dimensional motifs and discords

### ISSUE THREAD

**Issue by abhishekamte** [target/matrixprofile-ts#39]
Any plans to support multi-dimensionality?

Great library. Thanks!

**Comment by frankiecancino** [comment]
Definitely, it's on the roadmap/in the backlog. This and GPU functionality are two of the priorities.
And thank you! We appreciate it

**Comment by abhishekamte** [comment]
Great to hear that. What is the best way to ask queries w.r.t using this lib? I have a couple of questions on how the results I get when I use this on my data.

**Comment by vanbenschoten** [comment]
@abhishekamte do the tutorials help answer your questions? Let us know if there's something missing!

**Comment by frankiecancino** [comment]
Also, there is a Slack workspace we created, but haven't used it too much. The Slack URL is matrixprofile.slack.com if you're interested. We could advertise this more to incubate discussions around the different libraries out there for calculating the matrix profile.

**Comment by abhishekamte** [comment]
@vanbenschoten @frankiecancino, thank you for your replies. I have looked into both the tutorials hosted on Eamonn Keogh's home of the university's site and i dont think it is mentioned how we choose the value of m. I also had a couple of more questions
(1) based on the value of 'm' the discords may change. so taking the nyc taxi example mentioned in this repo as an example, how many datapoints are sufficient to have a good discord discovery. For example, if i have a minute data for a week and say i have m = 60 (one hour) is that a good place to start?

(2) can matrix profile be used for a streaming data system wherein the data is unbounded? I was thinking that maybe STAMPI can be used in such cases, so that you keep appending to your matrix profile. what are your thoughts? and in such a scenario how can i get the top discords but only the new ones.

**Comment by vanbenschoten** [comment]
@abhishekamte you're correct in that m will give you different discords: that's actually a feature of the algorithm. If you don't have a lot of insight into the nature of your data then you'll have to experiment with different values and just compare the results. However, if you have a sense of what a discord "should" look like, then you can set m appropriately. For instance, you may only care about long term trends over short term fluctuations, which means that m should be larger.

With respect to streaming, that's exactly the use case for STAMPI. And by definition all discords will be considered "new" since they haven't been observed before. If you want some sort of time decay weight applied to the Euclidean distance you can implement that as well, but such additional processing steps are currently outside the scope of this library (unless you contribute it back :).
