### ISSUE TITLE
What is the difference between matrixprofile and matrixprofile-ts?

### ISSUE THREAD

**Issue by RexKing6** [target/matrixprofile-ts#98]
So, I have no idea what the difference between these two packages? They both have pip, but there is no more update in matrixprofile-ts. Strangely, matrixprofile-ts has more stars. Can anyone answer my question?

**Comment by vanbenschoten** [comment]
@RexKing6 I can answer your question, as I am the original creator of matrixprofile-ts and co-creator of matrixprofile.  matrixprofile-ts was the first Python implementation of the Matrix Profile algorithms that I created while I was at Target. However, I left Target ~2 years ago and they no longer support this library. In the meantime, Tyler Marrs (who contributed heavily to matrixprofile-ts) and I designed a brand-new Matrix Profile implementation called _matrixprofile_ that is significantly more powerful and user-friendly than matrixprofile-ts.

This repo has more stars because we got lucky and hit the front page of Hacker News upon release ;) That said, matrixprofile has a substantially higher download rate (~67k in 6 months) than matrixprofile-ts (~74k in 2.5 years), so the community has definitely gravitated to _matrixprofile_ over _matrixprofile-ts_. So, if you're interested in using the Matrix Profile in Python/R/Golang, I'd highly recommend using _matrixprofile_.

**Comment by RexKing6** [comment]
Thank you! I am ready to use matrixprofile! Later when I have time, I also hope that I can contribute to the community, like mSTAMP.

**Comment by vanbenschoten** [comment]
Sounds great! mSTAMP would be a great contribution. Much appreciated!

**Comment by RexKing6** [comment]
I need to prepare my graduation thesis in the last year, so I will try mSTAMP when the thesis is nearing completion. Thank you!

**Comment by vanbenschoten** [comment]
Hey @RexKing6, hope the thesis is going well! Wanted to reach back out and see if you were interested in implementing mSTAMP in matrixprofile. No worries either way!

**Comment by RexKing6** [comment]
Yes, I am currently studying the application of matrix profile in anomaly detection! I expect to finish my thesis in March next year, after which I will spend part of the time participating in the development of mSTAMP.

**Comment by vanbenschoten** [comment]
Sounds great - congratulations on almost reaching the finish line!

**Comment by RexKing6** [comment]
Thanks!
